# Makefile generated by BNFC.

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestGramatyka

# Rules for building the parser.

ErrM.hs LexGramatyka.x PrintGramatyka.hs ParGramatyka.y TestGramatyka.hs : Gramatyka.cf
	bnfc --haskell Gramatyka.cf

%.hs : %.y
	happy --ghc --coerce --array --info $<

%.hs : %.x
	alex --ghc $<

TestGramatyka : TestGramatyka.hs ErrM.hs LexGramatyka.hs ParGramatyka.hs PrintGramatyka.hs
	ghc --make $< -o $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsGramatyka.hs AbsGramatyka.hs.bak ComposOp.hs ComposOp.hs.bak DocGramatyka.txt DocGramatyka.txt.bak ErrM.hs ErrM.hs.bak LayoutGramatyka.hs LayoutGramatyka.hs.bak LexGramatyka.x LexGramatyka.x.bak ParGramatyka.y ParGramatyka.y.bak PrintGramatyka.hs PrintGramatyka.hs.bak SharedString.hs SharedString.hs.bak SkelGramatyka.hs SkelGramatyka.hs.bak TestGramatyka.hs TestGramatyka.hs.bak XMLGramatyka.hs XMLGramatyka.hs.bak ASTGramatyka.agda ASTGramatyka.agda.bak ParserGramatyka.agda ParserGramatyka.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak Gramatyka.dtd Gramatyka.dtd.bak TestGramatyka LexGramatyka.hs ParGramatyka.hs ParGramatyka.info ParDataGramatyka.hs Makefile


# EOF
