{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintGrammar.
--   Generated by the BNF converter.

module PrintGrammar where

import qualified AbsGrammar
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsGrammar.Ident where
  prt _ (AbsGrammar.Ident i) = doc (showString i)

instance Print AbsGrammar.Program where
  prt i e = case e of
    AbsGrammar.Program topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print AbsGrammar.TopDef where
  prt i e = case e of
    AbsGrammar.FnDef id args block -> prPrec i 0 (concatD [doc (showString "def"), prt 0 id, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsGrammar.TopDef] where
  prt = prtList

instance Print AbsGrammar.Arg where
  prt i e = case e of
    AbsGrammar.Arg id -> prPrec i 0 (concatD [prt 0 id])
    AbsGrammar.CntsArg id -> prPrec i 0 (concatD [doc (showString "const"), prt 0 id])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsGrammar.Arg] where
  prt = prtList

instance Print AbsGrammar.Block where
  prt i e = case e of
    AbsGrammar.Block stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsGrammar.Stmt] where
  prt = prtList

instance Print AbsGrammar.Stmt where
  prt i e = case e of
    AbsGrammar.Empty -> prPrec i 0 (concatD [doc (showString ";")])
    AbsGrammar.BStmt block -> prPrec i 0 (concatD [prt 0 block])
    AbsGrammar.DeclCon id expr -> prPrec i 0 (concatD [doc (showString "const"), prt 0 id, doc (showString "="), prt 0 expr])
    AbsGrammar.DeclFun id args block -> prPrec i 0 (concatD [doc (showString "def"), prt 0 id, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
    AbsGrammar.Ass id expr -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsGrammar.TupleAss id exprs -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), doc (showString "("), prt 0 exprs, doc (showString ")"), doc (showString ";")])
    AbsGrammar.TupleAss1 args exprs -> prPrec i 0 (concatD [doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "="), doc (showString "("), prt 0 exprs, doc (showString ")"), doc (showString ";")])
    AbsGrammar.TupleAss2 args expr -> prPrec i 0 (concatD [doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsGrammar.Incr id -> prPrec i 0 (concatD [prt 0 id, doc (showString "++"), doc (showString ";")])
    AbsGrammar.Decr id -> prPrec i 0 (concatD [prt 0 id, doc (showString "--"), doc (showString ";")])
    AbsGrammar.Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsGrammar.RetTuple exprs -> prPrec i 0 (concatD [doc (showString "return"), doc (showString "("), prt 0 exprs, doc (showString ")"), doc (showString ";")])
    AbsGrammar.VRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsGrammar.Cond expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsGrammar.CondElse expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    AbsGrammar.While expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsGrammar.For id expr1 expr2 stmt -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 id, doc (showString "="), prt 0 expr1, doc (showString "to"), prt 0 expr2, doc (showString ")"), prt 0 stmt])
    AbsGrammar.ForIn id1 id2 stmt -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 id1, doc (showString "in"), prt 0 id2, doc (showString ")"), prt 0 stmt])
    AbsGrammar.Break -> prPrec i 0 (concatD [doc (showString "break")])
    AbsGrammar.Conti -> prPrec i 0 (concatD [doc (showString "continue")])
    AbsGrammar.SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
    AbsGrammar.PrInt expr -> prPrec i 0 (concatD [doc (showString "printInt"), doc (showString "("), prt 0 expr, doc (showString ")")])
    AbsGrammar.PrStr expr -> prPrec i 0 (concatD [doc (showString "printStr"), doc (showString "("), prt 0 expr, doc (showString ")")])
    AbsGrammar.Honk expr -> prPrec i 0 (concatD [doc (showString "honk"), doc (showString "("), prt 0 expr, doc (showString ")")])
    AbsGrammar.Error -> prPrec i 0 (concatD [doc (showString "error"), doc (showString "("), doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsGrammar.Expr where
  prt i e = case e of
    AbsGrammar.EVar id -> prPrec i 7 (concatD [prt 0 id])
    AbsGrammar.ELitInt n -> prPrec i 7 (concatD [prt 0 n])
    AbsGrammar.ELitTrue -> prPrec i 7 (concatD [doc (showString "true")])
    AbsGrammar.ELitFalse -> prPrec i 7 (concatD [doc (showString "false")])
    AbsGrammar.EApp id exprs -> prPrec i 7 (concatD [prt 0 id, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsGrammar.EString str -> prPrec i 7 (concatD [prt 0 str])
    AbsGrammar.EList exprs -> prPrec i 7 (concatD [doc (showString "["), prt 0 exprs, doc (showString "]")])
    AbsGrammar.EList1 expr1 expr2 -> prPrec i 7 (concatD [doc (showString "["), prt 0 expr1, doc (showString "]"), doc (showString "*"), prt 0 expr2])
    AbsGrammar.EAt id expr -> prPrec i 7 (concatD [prt 0 id, doc (showString "["), prt 0 expr, doc (showString "]")])
    AbsGrammar.Neg expr -> prPrec i 6 (concatD [doc (showString "-"), prt 7 expr])
    AbsGrammar.Not expr -> prPrec i 6 (concatD [doc (showString "!"), prt 7 expr])
    AbsGrammar.EMul expr1 mulop expr2 -> prPrec i 5 (concatD [prt 5 expr1, prt 0 mulop, prt 6 expr2])
    AbsGrammar.EAdd expr1 addop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 addop, prt 5 expr2])
    AbsGrammar.ERel expr1 relop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 relop, prt 4 expr2])
    AbsGrammar.EAnd expr1 expr2 -> prPrec i 2 (concatD [prt 3 expr1, doc (showString "&&"), prt 2 expr2])
    AbsGrammar.EOr expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "||"), prt 1 expr2])
    AbsGrammar.ELambda args block -> prPrec i 0 (concatD [doc (showString "\\"), prt 0 args, doc (showString "->"), prt 0 block])
    AbsGrammar.ELambdaS args block -> prPrec i 0 (concatD [doc (showString "lambda"), prt 0 args, doc (showString "->"), prt 0 block])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsGrammar.Expr] where
  prt = prtList

instance Print AbsGrammar.AddOp where
  prt i e = case e of
    AbsGrammar.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    AbsGrammar.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print AbsGrammar.MulOp where
  prt i e = case e of
    AbsGrammar.Times -> prPrec i 0 (concatD [doc (showString "*")])
    AbsGrammar.Div -> prPrec i 0 (concatD [doc (showString "/")])
    AbsGrammar.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print AbsGrammar.RelOp where
  prt i e = case e of
    AbsGrammar.LTH -> prPrec i 0 (concatD [doc (showString "<")])
    AbsGrammar.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsGrammar.GTH -> prPrec i 0 (concatD [doc (showString ">")])
    AbsGrammar.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsGrammar.EQU -> prPrec i 0 (concatD [doc (showString "==")])
    AbsGrammar.NE -> prPrec i 0 (concatD [doc (showString "!=")])

